server:
  port: 8080

spring:
  application.name: backend
  datasource:
#    url: jdbc:h2:mem:moviedb
#    url: jdbc:h2:file:./data/moviedb
    url: jdbc:postgresql://localhost:5432/moviedb
    username: username
    password: password
#    driverClassName: org.h2.Driver
    driverClassName: org.postgresql.Driver
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true # Enable H2 console served on /h2-console

logging.level:
  spring: DEBUG

custom:
  value: 42
