name: Tests and build

env:
  DOCKERHUB_USERNAME: nologin

on: 
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      # copy code to ubuntu machine
      - uses: actions/checkout@v4

      # install java 
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'maven'

      - name: Launch tests with Maven
        run: mvn -B clean test --file pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/polytech-2024
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: rg.fr-par.scw.cloud/polytech-2024/michelet/backend-image:v1
          context: .



